export const SEARCH_PRODUCT = "searchProduct"
export const FILTER_RATING_PRODUCT = "ratingProduct"
export const FILTER_PAYMENT_PRODUCT = "paymentProduct"
export const SORT_PRODUCT = "sortProduct"
export const ADD_TO_CART = "addToCart"
export const REMOVE_FROM_CART = "removeFromCart"
export const ADD_TO_ORDERS = "addToOrders"